#pragma once
// Auto-generated by CI before each build.
// For local builds this stays as "dev".
// CI overwrites FIRMWARE_VERSION with the git tag (v1.0.0) or short SHA (abc5797).
#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "dev"
#endif
